package cli

import (
	"encoding/json"
	"os"
	"slices"
	"testing"
)

// TestPyWrap checks pyWrap against Python's textwrap.wrap
// (testdata/textwrap.json was generated by it).
func TestPyWrap(t *testing.T) {
	data, err := os.ReadFile("testdata/textwrap.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Text  string
		Width int
		Lines []string
	}
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		if got := pyWrap(c.Text, c.Width); !slices.Equal(got, c.Lines) {
			t.Errorf("wrap(%q, %d):\n got %q\nwant %q", c.Text, c.Width, got, c.Lines)
		}
	}
}
