"""Generate ../tables.go from the running CPython's unicode database.

Run with the CPython whose re module is the reference (3.14):

    python3 internal/modules/pyre/testdata/gen_tables.py internal/modules/pyre/tables.go

The tables are what _sre consults for str patterns: \\d (str.isdecimal),
\\s (str.isspace), \\w (str.isalnum), sre's lower/upper (the first code
point of str.lower()/str.upper()), unicode_iscased, re._casefix's
_EXTRA_CASES, plus str.isprintable() and str.isidentifier() for the
parser's messages and group names, and a subset of unicodedata names
for \\N{...}.
"""

import re._casefix
import subprocess
import _sre
import sys
import unicodedata

MAX = sys.maxunicode + 1


def ranges(pred):
    out = []
    start = None
    for cp in range(MAX):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def fmt_ranges(name, rs):
    lines = ["var %s = []rangeTab{" % name]
    row = []
    for lo, hi in rs:
        row.append("{0x%x, 0x%x}," % (lo, hi))
        if len(row) == 6:
            lines.append("\t" + " ".join(row))
            row = []
    if row:
        lines.append("\t" + " ".join(row))
    lines.append("}")
    return "\n".join(lines)


def fmt_pairs(name, pairs):
    lines = ["var %s = []casePair{" % name]
    row = []
    for a, b in pairs:
        row.append("{0x%x, 0x%x}," % (a, b))
        if len(row) == 6:
            lines.append("\t" + " ".join(row))
            row = []
    if row:
        lines.append("\t" + " ".join(row))
    lines.append("}")
    return "\n".join(lines)


def first(s):
    return ord(s[0])


def main():
    out_path = sys.argv[1]
    lower = []
    upper = []
    for cp in range(MAX):
        c = chr(cp)
        lo = first(c.lower())
        assert lo == _sre.unicode_tolower(cp), hex(cp)
        if lo != cp:
            lower.append((cp, lo))
        up = first(c.upper())
        if up != cp:
            upper.append((cp, up))
        assert _sre.unicode_iscased(cp) == (lo != cp or up != cp), hex(cp)

    parts = [
        "// Code generated by testdata/gen_tables.py from CPython %s (Unicode %s); DO NOT EDIT."
        % (sys.version.split()[0], unicodedata.unidata_version),
        "",
        "package pyre",
        "",
        fmt_ranges("tabDecimal", ranges(lambda cp: chr(cp).isdecimal())),
        "",
        fmt_ranges("tabSpace", ranges(lambda cp: chr(cp).isspace())),
        "",
        fmt_ranges("tabAlnum", ranges(lambda cp: chr(cp).isalnum())),
        "",
        fmt_ranges("tabAlpha", ranges(lambda cp: chr(cp).isalpha())),
        "",
        fmt_ranges("tabPrintable", ranges(lambda cp: chr(cp).isprintable())),
        "",
        fmt_ranges("tabIDStart", ranges(lambda cp: chr(cp).isidentifier())),
        "",
        fmt_ranges("tabIDContinue", ranges(lambda cp: ("a" + chr(cp)).isidentifier())),
        "",
        fmt_pairs("tabLower", lower),
        "",
        fmt_pairs("tabUpper", upper),
        "",
    ]
    extra = ["// extraCases is re._casefix._EXTRA_CASES.", "var extraCases = map[rune][]rune{"]
    for k in sorted(re._casefix._EXTRA_CASES):
        v = re._casefix._EXTRA_CASES[k]
        extra.append("\t0x%x: {%s}," % (k, ", ".join("0x%x" % x for x in v)))
    extra.append("}")
    parts.append("\n".join(extra))
    parts.append("")

    # A subset of unicodedata.lookup() names: Latin, Greek, punctuation,
    # currency, letterlike, arrows, math, box drawing and shapes. CJK
    # unified ideographs and Hangul syllables are computed.
    names = ["// charNames is a subset of the unicodedata names \\N{...} looks up.", "var charNames = map[string]rune{"]
    seen = set()
    for lo, hi in [(0x20, 0x250), (0x370, 0x400), (0x2000, 0x2070), (0x20A0, 0x20C1),
                   (0x2100, 0x2300), (0x2500, 0x2600)]:
        for cp in range(lo, hi):
            n = unicodedata.name(chr(cp), "")
            if n and n not in seen:
                seen.add(n)
                names.append('\t"%s": 0x%x,' % (n, cp))
    # Common aliases (NameAliases.txt) lookup() accepts.
    for alias in ["NULL", "CHARACTER TABULATION", "LINE FEED", "LINE TABULATION",
                  "FORM FEED", "CARRIAGE RETURN", "ESCAPE", "DELETE", "NO-BREAK SPACE",
                  "TAB", "LF", "CR", "NUL", "ESC", "DEL", "NBSP", "SP", "VT", "FF",
                  "NEW LINE", "END OF LINE", "BACKSPACE", "BELL", "ALERT",
                  "BYTE ORDER MARK", "BOM", "ZWSP", "ZWNJ", "ZWJ"]:
        try:
            c = unicodedata.lookup(alias)
        except KeyError:
            continue
        if len(c) == 1 and alias not in seen:
            seen.add(alias)
            names.append('\t"%s": 0x%x,' % (alias, ord(c)))
    names.append("}")
    parts.append("\n".join(names))
    parts.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(parts))
    subprocess.run(["gofmt", "-w", out_path], check=True)


if __name__ == "__main__":
    main()
