package modules

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/giraffesyo/understudy/internal/agentproto"
	"github.com/giraffesyo/understudy/internal/modules/args"
	"github.com/giraffesyo/understudy/internal/modules/pyre"
)

func init() {
	Register(cronModule, "cron", "ansible.builtin.cron")
}

var cronSpec = args.Spec{
	"name":         {Required: true},
	"user":         {},
	"job":          {Aliases: []string{"value"}},
	"cron_file":    {},
	"state":        {Default: "present", Choices: []string{"present", "absent"}},
	"backup":       {Type: "bool", Default: false},
	"minute":       {Default: "*"},
	"hour":         {Default: "*"},
	"day":          {Default: "*", Aliases: []string{"dom"}},
	"month":        {Default: "*"},
	"weekday":      {Default: "*", Aliases: []string{"dow"}},
	"special_time": {Choices: []string{"reboot", "yearly", "annually", "monthly", "weekly", "daily", "hourly"}},
	"disabled":     {Type: "bool", Default: false},
	"env":          {Type: "bool", Default: false},
	"insertafter":  {},
	"insertbefore": {},
}

const cronMarker = "#Ansible: "

// crontab is the module's CronTab: the lines of a user crontab (read and
// installed with the crontab CLI) or of a cron file.
type crontab struct {
	env      *RunEnv
	user     string
	cronFile string // "" for a user crontab
	cronCmd  string
	lines    []string
	existing string
}

var crontabHeaders = []*regexp.Regexp{
	regexp.MustCompile(`^# DO NOT EDIT THIS FILE - edit the master and reinstall\.`),
	regexp.MustCompile(`^# \(/tmp/.*installed on.*\)`),
	regexp.MustCompile(`^# \(.*version.*\)`),
}

func (c *crontab) read() *agentproto.Result {
	if c.cronFile != "" {
		data, err := os.ReadFile(c.cronFile)
		if err != nil {
			return nil // a missing cron file is an empty one
		}
		c.existing = string(data)
		c.lines = pyStrSplitlines(c.existing)
		return nil
	}
	rc, out, _ := runCommand(c.env, []string{"/bin/sh", "-c", c.readCmd()}, cmdOpts{})
	if rc != 0 && rc != 1 { // 1 can mean that there are no jobs
		return &agentproto.Result{Failed: true, Msg: "Task failed: Module failed: Unable to read crontab"}
	}
	c.existing = out
	for count, l := range pyStrSplitlines(out) {
		header := false
		if count <= 2 {
			for _, re := range crontabHeaders {
				if re.MatchString(l) {
					header = true
				}
			}
		}
		if !header {
			c.lines = append(c.lines, l)
			continue
		}
		// Drop the first occurrence of the header line (and its newline).
		re := regexp.MustCompile(regexp.QuoteMeta(l) + `[\r\n]?`)
		if loc := re.FindStringIndex(c.existing); loc != nil {
			c.existing = c.existing[:loc[0]] + c.existing[loc[1]:]
		}
	}
	return nil
}

func currentUserName() string {
	if u, err := user.Current(); err == nil {
		return u.Username
	}
	return os.Getenv("USER")
}

func (c *crontab) userFlag() string {
	if c.user != "" && currentUserName() != c.user {
		return "-u " + shQuote(c.user)
	}
	return ""
}

func (c *crontab) readCmd() string {
	return fmt.Sprintf("%s %s %s", c.cronCmd, c.userFlag(), "-l")
}

func (c *crontab) writeCmd(path string) string {
	return fmt.Sprintf("%s %s %s", c.cronCmd, c.userFlag(), shQuote(path))
}

func (c *crontab) render() string {
	r := strings.Join(c.lines, "\n")
	if r != "" {
		r = strings.TrimRight(r, "\r\n") + "\n"
	}
	return r
}

// write installs the rendered crontab (or saves it to backupFile).
func (c *crontab) write(backupFile string) *agentproto.Result {
	data := []byte(c.render())
	switch {
	case backupFile != "":
		if err := os.WriteFile(backupFile, data, 0o600); err != nil {
			return moduleCrash(err)
		}
		return nil
	case c.cronFile != "":
		_, statErr := os.Stat(c.cronFile)
		if err := os.WriteFile(c.cronFile, data, 0o644); err != nil {
			return moduleCrash(err)
		}
		if os.IsNotExist(statErr) {
			_ = os.Chmod(c.cronFile, 0o644)
		}
		return nil
	}
	f, err := pyMkstemp("", "crontab")
	if err != nil {
		return moduleCrash(err)
	}
	path := f.Name()
	_ = f.Chmod(0o666)
	_, err = f.Write(data)
	f.Close()
	if err != nil {
		return moduleCrash(err)
	}
	rc, out, stderr := runCommand(c.env, []string{"/bin/sh", "-c", c.writeCmd(path)}, cmdOpts{})
	os.Remove(path)
	if rc != 0 {
		return &agentproto.Result{Failed: true, Msg: "Failed to install new cronfile: " + path,
			RC: &rc, Stdout: out, Stderr: stderr}
	}
	return nil
}

func (c *crontab) comment(name string) string { return cronMarker + name }

// findJob is find_job: by the marker comment, else by an exact job line
// (adopting it under the name). The third element flags an adoption.
func (c *crontab) findJob(name, job string) []string {
	var comment *string
	for _, l := range c.lines {
		if comment != nil {
			if *comment == name {
				return []string{*comment, l}
			}
			comment = nil
		} else if strings.HasPrefix(l, cronMarker) {
			s := strings.ReplaceAll(l, cronMarker, "")
			comment = &s
		}
	}
	if job != "" {
		for i, l := range c.lines {
			if l != job {
				continue
			}
			prev := i - 1
			if prev < 0 { // Python's lines[-1]
				prev = len(c.lines) - 1
			}
			if !strings.HasPrefix(c.lines[prev], cronMarker) {
				c.lines = append(c.lines[:i], append([]string{c.comment(name)}, c.lines[i:]...)...)
				return []string{c.lines[i], l, "True"}
			} else if name != "" && c.lines[prev] == c.comment("None") {
				c.lines[prev] = c.comment(name)
				return []string{c.lines[prev], l, "True"}
			}
		}
	}
	return nil
}

// updateJob replaces (job != nil) or removes the line after name's marker.
func (c *crontab) updateJob(name string, job *string) {
	marker := c.comment(name)
	var out []string
	var comment *string
	for _, l := range c.lines {
		switch {
		case comment != nil:
			if job != nil {
				out = append(out, *comment, *job)
			}
			comment = nil
		case l == marker:
			s := l
			comment = &s
		default:
			out = append(out, l)
		}
	}
	c.lines = out
}

func (c *crontab) envRe(name string) (*pyre.Pattern, *agentproto.Result) {
	return pyCompile("^" + name + "=")
}

func (c *crontab) findEnv(re *pyre.Pattern) int {
	for i, l := range c.lines {
		if re.Match(l, 0, -1) != nil {
			return i
		}
	}
	return -1
}

// updateEnv replaces (decl != nil) or removes every declaration of re.
func (c *crontab) updateEnv(re *pyre.Pattern, decl *string) {
	var out []string
	for _, l := range c.lines {
		if re.Match(l, 0, -1) != nil {
			if decl != nil {
				out = append(out, *decl)
			}
			continue
		}
		out = append(out, l)
	}
	c.lines = out
}

func (c *crontab) jobNames() []any {
	out := []any{}
	for _, l := range c.lines {
		if strings.HasPrefix(l, cronMarker) {
			out = append(out, strings.ReplaceAll(l, cronMarker, ""))
		}
	}
	return out
}

var cronEnvLine = regexp.MustCompile(`^\S+=`)

func (c *crontab) envNames() []any {
	out := []any{}
	for _, l := range c.lines {
		if cronEnvLine.MatchString(l) {
			out = append(out, strings.SplitN(l, "=", 2)[0])
		}
	}
	return out
}

func (c *crontab) isEmpty() bool {
	for _, l := range c.lines {
		if strings.TrimSpace(l) != "" {
			return false
		}
	}
	return true
}

func (c *crontab) header() string {
	if c.cronFile != "" {
		return c.cronFile
	}
	if c.user != "" {
		return fmt.Sprintf("crontab for user %q", c.user)
	}
	return "crontab"
}

// cronModule ports ansible.builtin.cron.
func cronModule(env *RunEnv, rawArgs map[string]any) *agentproto.Result {
	if err := cronSpec.MutuallyExclusive(rawArgs, []string{"insertafter", "insertbefore"}); err != nil {
		return agentproto.Fail("%v", err)
	}
	p, err := cronSpec.Parse(rawArgs)
	if err != nil {
		return agentproto.Fail("%v", err)
	}
	name := p.Str("name")
	userName := p.Str("user")
	job, hasJob := p.Str("job"), p.Has("job")
	cronFile := pyExpandPath(p.Str("cron_file"))
	state := p.Str("state")
	backup := p.Bool("backup")
	minute, hour, day, month, weekday := p.Str("minute"), p.Str("hour"), p.Str("day"), p.Str("month"), p.Str("weekday")
	special := p.Str("special_time")
	disabled := p.Bool("disabled")
	isEnv := p.Bool("env")
	insertAfter, insertBefore := p.Str("insertafter"), p.Str("insertbefore")
	doInstall := state == "present"

	var warnings []any
	if cronFile != "" {
		if cronFile == "/etc/crontab" {
			return agentproto.Fail("Will not manage /etc/crontab via cron_file, see documentation.")
		}
		base := filepath.Base(cronFile)
		if !regexp.MustCompile(`(?i)^[A-Z0-9_-]+$`).MatchString(base) {
			warnings = append(warnings, fmt.Sprintf("Filename portion of cron_file (%q) should consist"+
				" solely of upper- and lower-case letters, digits, underscores, and hyphens", base))
		}
	}

	cmd, err := getBinPathIn(envPATH(env), "crontab")
	if err != nil {
		return agentproto.Fail("%v", err)
	}
	c := &crontab{env: env, user: userName, cronCmd: cmd}
	if cronFile != "" {
		if filepath.IsAbs(cronFile) {
			c.cronFile = cronFile
		} else {
			c.cronFile = filepath.Join("/etc/cron.d", cronFile)
		}
	}
	if fail := c.read(); fail != nil {
		return fail
	}

	withWarnings := func(res *agentproto.Result) *agentproto.Result {
		if len(warnings) > 0 {
			if res.Extra == nil {
				res.Extra = map[string]any{}
			}
			res.Extra["warnings"] = warnings
		}
		return res
	}
	fail := func(msg string) *agentproto.Result {
		return withWarnings(agentproto.Fail("%s", msg))
	}

	diff := map[string]any{}
	if env.DiffMode {
		diff["before"] = c.existing
		diff["before_header"] = c.header()
	}

	if special != "" {
		for _, v := range []string{minute, hour, day, month, weekday} {
			if v != "*" {
				return fail("You cannot combine special_time with any of the time or day/date parameters.")
			}
		}
	}
	if doInstall {
		if cronFile != "" && userName == "" {
			return fail("To use cron_file=... parameter you must specify user=... as well")
		}
		if !hasJob {
			return fail("You must specify 'job' to install a new cron job or variable")
		}
		if (insertAfter != "" || insertBefore != "") && !isEnv {
			return fail("Insertafter and insertbefore parameters are valid only with env=yes")
		}
	}

	backupFile := ""
	if backup && !env.CheckMode {
		f, err := pyMkstemp("", "crontab")
		if err != nil {
			return moduleCrash(err)
		}
		backupFile = f.Name()
		f.Close()
		if res := c.write(backupFile); res != nil {
			return res
		}
	}

	changed := false
	if isEnv {
		if strings.Contains(name, " ") {
			return fail("Invalid name for environment variable")
		}
		decl := name + `="` + job + `"`
		re, bad := c.envRe(name)
		if bad != nil {
			return withWarnings(bad)
		}
		idx := c.findEnv(re)
		if doInstall {
			if idx < 0 {
				other := insertAfter
				if other == "" {
					other = insertBefore
				}
				if other == "" {
					c.lines = append([]string{decl}, c.lines...)
				} else {
					ore, bad := c.envRe(other)
					if bad != nil {
						return withWarnings(bad)
					}
					oi := c.findEnv(ore)
					if oi < 0 {
						return fail(fmt.Sprintf("Variable named '%s' not found.", other))
					}
					if insertAfter != "" {
						oi++
					}
					c.lines = append(c.lines[:oi], append([]string{decl}, c.lines[oi:]...)...)
				}
				changed = true
			} else if c.lines[idx] != decl {
				c.updateEnv(re, &decl)
				changed = true
			}
		} else if idx >= 0 {
			c.updateEnv(re, nil)
			changed = true
		}
	} else if doInstall {
		trimmed := strings.Trim(job, "\r\n")
		if strings.ContainsAny(trimmed, "\r\n") {
			warnings = append(warnings, "Job should not contain line breaks")
		}
		line := c.jobLine(minute, hour, day, month, weekday, trimmed, special, disabled)
		old := c.findJob(name, line)
		if len(old) == 0 {
			c.lines = append(c.lines, c.comment(name), line)
			changed = true
		}
		if len(old) > 0 && old[1] != line {
			c.updateJob(name, &line)
			changed = true
		}
		if len(old) > 2 {
			c.updateJob(name, &line)
			changed = true
		}
	} else if old := c.findJob(name, ""); len(old) > 0 {
		c.updateJob(name, nil)
		changed = true
		if c.cronFile != "" && c.isEmpty() {
			if env.DiffMode {
				diff["after"] = ""
				diff["after_header"] = "/dev/null"
			} else {
				diff = map[string]any{}
			}
			if env.CheckMode {
				changed = isFile(c.cronFile)
			} else {
				changed = os.Remove(c.cronFile) == nil
			}
			return withWarnings(&agentproto.Result{Changed: changed, Diff: diff,
				Extra: map[string]any{"cron_file": cronFile, "state": state}})
		}
	}

	// No change to the entries, but the crontab needs a final newline.
	if !changed && c.existing != "" && !strings.HasSuffix(c.existing, "\r") && !strings.HasSuffix(c.existing, "\n") {
		changed = true
	}

	res := &agentproto.Result{Changed: changed, Extra: map[string]any{
		"jobs": c.jobNames(), "envs": c.envNames(),
	}}
	if changed {
		if !env.CheckMode {
			if fail := c.write(""); fail != nil {
				return withWarnings(fail)
			}
		}
		if env.DiffMode {
			diff["after"] = c.render()
			diff["after_header"] = c.header()
			res.Diff = diff
		}
	}
	if backup && !env.CheckMode {
		if changed {
			res.Extra["backup_file"] = backupFile
		} else {
			os.Remove(backupFile)
		}
	}
	if cronFile != "" {
		res.Extra["cron_file"] = cronFile
	}
	return withWarnings(res)
}

func (c *crontab) jobLine(minute, hour, day, month, weekday, job, special string, disabled bool) string {
	prefix := ""
	if disabled {
		prefix = "#"
	}
	if special != "" {
		if c.cronFile != "" {
			return fmt.Sprintf("%s@%s %s %s", prefix, special, c.user, job)
		}
		return fmt.Sprintf("%s@%s %s", prefix, special, job)
	}
	if c.cronFile != "" {
		return fmt.Sprintf("%s%s %s %s %s %s %s %s", prefix, minute, hour, day, month, weekday, c.user, job)
	}
	return fmt.Sprintf("%s%s %s %s %s %s %s", prefix, minute, hour, day, month, weekday, job)
}

// pyMkstemp is tempfile.mkstemp(prefix=prefix, dir=dir): a new 0600 file
// with a Python-style random name, in the temp dir when dir is "".
func pyMkstemp(dir, prefix string) (*os.File, error) {
	if dir == "" {
		dir = pyGettempdir()
	}
	for {
		f, err := os.OpenFile(filepath.Join(dir, prefix+pyTempName()), os.O_RDWR|os.O_CREATE|os.O_EXCL, 0o600)
		if os.IsExist(err) {
			continue
		}
		return f, err
	}
}
